[project]
name = "panel-graphic-walker"
channels = ["pyviz/label/dev", "conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[tasks]
install = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[environments]
test-310 = ["py310", "compile", "test-core", "test", "test-unit-task"]
test-311 = ["py311", "compile", "test-core", "test", "test-unit-task"]
test-312 = ["py312", "compile", "test-core", "test", "test-unit-task"]
test-ui = ["py312", "compile", "test-core", "test", "test-ui"]
test-core = ["py312", "compile", "test-core", "test-unit-task"]
build = ["py312", "build", "compile"]
compile = ["py312", "compile"]
lint = { features = ["lint"], no-default-feature = true }

[dependencies]
python = ">=3.10"
panel = ">=1.6.1"
packaging = "*"
narwhals = "*"

[host-dependencies]
pip = "*"
setuptools = ">=61"
setuptools-scm = "*"
hatchling = "*"
hatch-vcs = "*"
nodejs = ">=18"
esbuild = "*"

[feature.py310.dependencies]
python = "3.10.*"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

# =============================================
# ================== TEST =====================
# =============================================

[feature.test-core.dependencies]
pytest = ">=6"
pytest-asyncio = "*"
pytest-cov = "*"
pytest-rerunfailures = "*"
pytest-xdist = "*"
mypy = "*"

[feature.test-core.pypi-dependencies]
panel-graphic-walker = { path = ".", editable = true }

[feature.test-core.pypi-options]
no-build-isolation = ["panel-graphic-walker"]

[feature.test.dependencies]
aiohttp = "*"
dask = "*"
duckdb = "*"
ibis-framework = "*"
fastparquet = "*"
polars = "*"
pygwalker = "*"

[feature.test.pypi-dependencies]
gw-dsl-parser = "*"

[feature.test-unit-task.tasks]
test = "pytest"
test-coverage = "pytest --cov=panel_gwalker --cov-report=xml --cov-report=term-missing"

[feature.test-ui]
channels = ["microsoft"]

[feature.test-ui.dependencies]
playwright = { version = "*", channel = "microsoft" }
pytest-playwright = { version = "*", channel = "microsoft" }

[feature.test-ui.tasks]
_install-ui = 'playwright install chromium'

[feature.test-ui.tasks.test-ui]
cmd = 'pytest ./tests/ui --ui --browser chromium -n logical --dist loadgroup --reruns 3 --reruns-delay 10'
depends-on = ["_install-ui"]

# =============================================
# ================== BUILD ====================
# =============================================

[feature.build.dependencies]
python-build = "*"
twine = "*"
wheel = "*"

[feature.build.tasks]
build-wheel = "python -m build --no-isolation ."
check-wheel = "twine check dist/*"

# =============================================
# ================= COMPILE ===================
# =============================================

[feature.compile.dependencies]
nodejs = ">=18"
esbuild = "*"

[feature.compile.tasks]
compile = "panel compile panel_gwalker"
compile-develop = "panel compile panel_gwalker --build-dir build --watch"

# =============================================
# ================== LINT =====================
# =============================================

[feature.lint.dependencies]
pre-commit = "*"

[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"
